development:
  adapter: mysql2
  reconnect: true
  database: rails_dev
  username: <%= APP_CONFIG['database_username'] %>
  password: <%= APP_CONFIG['database_password'] %>
  host: <%= APP_CONFIG['database_host'] %>

test:
  adapter: mysql2
  reconnect: true
  database: rails_test
  username: <%= APP_CONFIG['database_username'] %>
  password: <%= APP_CONFIG['database_password'] %>
  host: <%= APP_CONFIG['database_host'] %>

production:
  adapter: mysql2
  reconnect: true
  database: rails_prod
  username: <%= APP_CONFIG['database_username'] %>
  password: <%= APP_CONFIG['database_password'] %>
  host: <%= APP_CONFIG['database_host'] %>
